### ISSUE TITLE
Corrupted files / invalid images

### ISSUE THREAD

**Issue by mfidino** [mfidino/uwin_issues#1]
- S05-SFP3-SP18 #2296-2978
- S09-KTP1-SP18 #2224-2642
- D04-RDP1-WI18 #3967-4247
- D06-KCG1-SP18 – photo #1914 corrupted and did not upload into database from SD card (all of 1913 photos were fine)

**Comment by mfidino** [comment]
Perhaps with this type of issue we need to remove all data within the database (for corrupt images).

**Comment by grbarnas** [comment]
D02-SCP1-SP18 - last 226 images invalid

**Comment by mfidino** [comment]
I've deleted these records from the database. In the future please specify number range instead of "last x photos" (i.e., photos 3290 to 3570). I still verify that these images are indeed corrupted but it makes hunting them down easier. 

Photo 1914 from D06-KCG1-SP18 was not in the database so I ignored it.

**Comment by grbarnas** [comment]
Will do.
