### ISSUE TITLE
Tagged photos need to be removed for one site

### ISSUE THREAD

**Issue by grbarnas** [mfidino/uwin_issues#5]
In Compare IDs, the tags for the photos of D05-MIA1-SU16 are vastly different and suggest that something happened with the orders of the photos in the tagging modules? We discussed removing the tagged photos for this site and completing two whole new modules to tag the photos again.

**Comment by mfidino** [comment]
I have removed the tags from these photos for D05-MIA1-SU16. @grbarnas let me know when you have set this site up to be retagged (i.e., have removed the finished part from the SU16 excel file) and I will close this issue.

**Comment by grbarnas** [comment]
SU16 excel file has been updated to have the site retagged by two people
