### ISSUE TITLE
Photos need to be removed from database?

### ISSUE THREAD

**Issue by grbarnas** [mfidino/uwin_issues#6]
This was a leftover issue from Edder, so this is all from information left by him about R04-SCH1-FA16: first 45 photos are from check, 46 is from pull (all of these photos are from R04-SCH1); the rest of the photos are from S05-LNC1-SU16.

**Comment by mfidino** [comment]
There were photos in the R04-SCH1-FA16 folder that were actually from S05-LNC1-SU16. Those photos were not linked to the database in any way so I simply deleted them.  However, I checked in the database on S05-LNC1-SU16 and there are TWO folders that are linked to this site:

- S05-LNC1
- S05-LNC1 (Real)

The second one has all of the photos, while the first one does not. I deleted (in the database) the links to the first of the two folders. @grbarnas  it does not look as if these photos have been tagged (though I think they should have been). Can you set these up to get tagged? Following this I will close the issue.

**Comment by grbarnas** [comment]
Just to clarify, does S05-LNC1-SU16 need to be tagged by two people or just one? According to the phototag spreadsheet, it was tagged once by Peggy.

**Comment by mfidino** [comment]
By 2 people (both of which should not be Peggy) as I think I deleted her tags (they were done on the photo set I removed)

**Comment by grbarnas** [comment]
Got it. This site is all set to be tagged by two new people.
