### ISSUE TITLE
A new column in the CameraLocations table

### ISSUE THREAD

**Issue by mfidino** [mfidino/uwin_issues#7]
In the Camera Locations table, I’d like to add in a column for “current?” and “inpc?”, responses would be a yes/no or check box. This was designated for each site in the old db and was very helpful for reporting (Is it a current site or retired? Is it an iNPC site?).

**Comment by mfidino** [comment]
Hey @llehrer, this will be way easier if I just add a column and do not include it in the camera locations form. Would that work for you? The camera locations form is basically just the table anyways.

**Comment by llehrer** [comment]
oh yea, the table is just fine. thanks.

**Comment by mfidino** [comment]
Okay @llehrer I added a 'Retired' column that you can check if you the site is no longer sampled. I think it makes more sense that way so we don't have to check everything as current (and then go back and uncheck when they get retired).

Let me know if that works for you can I can close this.

**Comment by llehrer** [comment]
Sounds good. Can you do the same for INPC?

**Comment by mfidino** [comment]
Done and done.

**Comment by llehrer** [comment]
awesome thank you! let me know when you are out and I will check the INPC sites on the table

**Comment by mfidino** [comment]
@llehrer I've closed out of the database

**Comment by llehrer** [comment]
cool. they are now indicated in the db. @grbarnas no rush but at some point could you go through our current transect lists and check which sites we are sampling and which have been retired? thanks!

**Comment by grbarnas** [comment]
Yes, can do!
