### ISSUE TITLE
Multiple entries in CameraLocations table

### ISSUE THREAD

**Issue by mfidino** [mfidino/uwin_issues#8]
Two entries for SFP3 in same table, one seems to be blank.

**Comment by mfidino** [comment]
I deleted the one record that was blank. However, one season's worth of photos were attributed to that record so before deleting I moved them over to the correct record.

Hey  @llehrer why do the UTMs at this site (and this site only) have decimal places?

**Comment by llehrer** [comment]
I suspect that they were taken using someone's phone or something and when entered they weren't rounded.
